# We only include the CSV template
{{ if .Values.bundleGeneration }}
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: {{ .Values.csv.capabilities }}
    categories: {{ .Values.csv.categories }}
    containerImage: {{ .Values.image }}
    description: {{ .Values.csv.description }}
    operators.operatorframework.io/internal-objects: '["wasmplugins.extensions.istio.io","destinationrules.networking.istio.io","envoyfilters.networking.istio.io","gateways.networking.istio.io","proxyconfigs.networking.istio.io","serviceentries.networking.istio.io","sidecars.networking.istio.io","virtualservices.networking.istio.io","workloadentries.networking.istio.io","workloadgroups.networking.istio.io","authorizationpolicies.security.istio.io","peerauthentications.security.istio.io","requestauthentications.security.istio.io","telemetries.telemetry.istio.io"]'
    repository: https://github.com/maistra/istio-operator/tree/maistra-3.0
    support: {{ .Values.csv.support }}
    features.operators.openshift.io/disconnected: {{ .Values.csv.olmFeatureDisconnected }}
    features.operators.openshift.io/fips-compliant: {{ .Values.csv.olmFeatureFIPSCompliant }}
    features.operators.openshift.io/proxy-aware: {{ .Values.csv.olmFeatureProxyAware }}
    features.operators.openshift.io/tls-profiles: {{ .Values.csv.olmFeatureTLSProfiles }}
    features.operators.openshift.io/token-auth-aws: {{ .Values.csv.olmFeatureTokenAuthAWS }}
    features.operators.openshift.io/token-auth-azure: {{ .Values.csv.olmFeatureTokenAuthAzure }}
    features.operators.openshift.io/token-auth-gcp: {{ .Values.csv.olmFeatureTokenAuthGCP }}
    features.operators.openshift.io/cnf: {{ .Values.csv.olmFeatureCNF }}
    features.operators.openshift.io/cni: {{ .Values.csv.olmFeatureCNI }}
    features.operators.openshift.io/csi: {{ .Values.csv.olmFeatureCSI }}
  name: {{ .Values.name }}.v{{ .Values.csv.version }}
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  description: |-
{{ indent 4 .Values.csv.longDescription }}
  displayName: {{ .Values.csv.displayName }}
  icon:
  - base64data: {{ .Values.csv.icon.base64data }}
    mediatype: {{ .Values.csv.icon.mediatype }}
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
{{- range .Values.csv.keywords }}
  - {{ . }}
{{- end }}
  links:
  - name: Istio Project
    url: https://istio.io
  maintainers:
  - email: istio-feedback@redhat.com
    name: OpenShift Service Mesh Team
  maturity: alpha
  provider:
    name: Red Hat, Inc.
  version: {{ .Values.csv.version }}
{{ end }}
