# Source: istiod-remote/templates/reader-serviceaccount
apiVersion: v1
kind: ServiceAccount
  {{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
    {{- end }}
    {{- end }}
metadata:
  name: istio-reader-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: "2.5.2"
    app: istio-reader
    release: {{ .Release.Name }}
