apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: sail-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: IstioHelmInstall is the Schema for the istiohelminstalls API
      displayName: Istio Helm Install
      kind: IstioHelmInstall
      name: istiohelminstalls.maistra.io
      version: v1
  description: Installs Service Mesh (ALPHA BUILD)
  displayName: Service Mesh Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - service mesh
  - istio
  - envoy
  links:
  - name: Sail Operator
    url: https://sail-operator.domain
  maturity: alpha
  provider:
    name: Service Mesh Operator
    url: https://github.com/maistra/istio-operator
  version: 0.0.0
