{{- if and .Values.cni.enabled (has "v2.6" .Values.cni.supportedReleases) (eq .Values.cni.instanceVersion "v2.6") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cni.defaultResourceName }}
  namespace: {{ .Release.Namespace }}
{{- end }}
