{{ $gateway := index .Values "gateways" "istio-egressgateway" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $gateway.name | default "istio-egressgateway" }}-sds
  namespace: {{ $gateway.namespace | default .Release.Namespace }}
  labels:
    maistra-version: "2.1.0"
    release: {{ .Release.Name }}
    istio.io/rev: {{ .Values.revision | default "default" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $gateway.name | default "istio-egressgateway" }}-sds
subjects:
  - kind: ServiceAccount
    name: {{ $gateway.name | default "istio-egressgateway" }}-service-account
---
